// AUTOGENERATED by pkg/hicli/cmdspec/print; do not edit.

import type { BotCommandsEventContent } from "./mxtypes.ts"

export type CommandName =
	"meow {meow}"
	| "join {room_reference} {reason}"
	| "leave"
	| "invite {user_id} {reason}"
	| "kick {user_id} {reason}"
	| "ban {user_id} {reason}"
	| "myroomnick {name}"
	| "myroomavatar"
	| "globalnick {name}"
	| "globalavatar"
	| "roomname"
	| "roomavatar"
	| "redact {event_id} {reason}"
	| "raw {event_type} {json}"
	| "unencryptedraw {event_type} {json}"
	| "rawstate {event_type} {state_key} {json}"
	| "discardsession"

export default BotCommandsEventContent
