// Copyright (c) 2025 Tulir Asokan
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

package main

import (
	"encoding/json"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"go.mau.fi/util/exbytes"
	"go.mau.fi/util/exerrors"
	"maunium.net/go/mautrix/event/cmdschema/testdata"

	"go.mau.fi/gomuks/pkg/hicli/cmdspec"
)

const typescriptTemplate = `// AUTOGENERATED by pkg/hicli/cmdspec/print; do not edit.

import type { BotCommandList } from "./mxtypes.ts"

export type CommandName =
	%s

export default BotCommandList
`

func main() {
	names := make([]string, len(cmdspec.CommandDefinitions))
	for i, spec := range cmdspec.CommandDefinitions {
		names[i] = fmt.Sprintf("%q", spec.Command)
		if !spec.IsValid() {
			panic(fmt.Errorf("%s is not valid", spec.Command))
		}
	}
	output := exerrors.Must(json.Marshal(cmdspec.CommandDefinitions))
	if len(os.Args) > 1 && os.Args[1] != "-" {
		exerrors.PanicIfNotNil(os.WriteFile(os.Args[1], output, 0644))
		if len(os.Args) > 2 {
			cmdNames := strings.Join(names, "\n\t| ")

			exerrors.PanicIfNotNil(os.WriteFile(os.Args[2], []byte(fmt.Sprintf(typescriptTemplate, cmdNames)), 0644))

			if len(os.Args) > 3 {
				dumpFS(testdata.FS, os.Args[3])
			}
		}
	} else {
		fmt.Println(exbytes.UnsafeString(output))
	}
}

func dumpFS(data fs.ReadDirFS, dir string) {
	exerrors.PanicIfNotNil(os.MkdirAll(dir, 0755))
	for _, file := range exerrors.Must(data.ReadDir(".")) {
		if file.IsDir() {
			dumpFS(exerrors.Must(fs.Sub(data, file.Name())).(fs.ReadDirFS), filepath.Join(dir, file.Name()))
		} else if strings.HasSuffix(file.Name(), ".json") {
			f := exerrors.Must(data.Open(file.Name()))
			out := exerrors.Must(os.OpenFile(filepath.Join(dir, file.Name()), os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0644))
			exerrors.Must(io.Copy(out, f))
			_ = f.Close()
			_ = out.Close()
		}
	}
}
